# Generated by Django 2.2.16 on 2021-10-09 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20211009_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='pub_date',
        ),
    ]
