# Generated by Django 2.2.16 on 2021-10-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20211011_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='category_name',
            new_name='name',
        ),
    ]
