# Generated by Django 2.2.16 on 2021-10-12 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20211011_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2021)], verbose_name='Год выпуска'),
        ),
    ]
