# Generated by Django 2.2.16 on 2021-10-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20211012_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(to='media.Genres', verbose_name='Жанр'),
        ),
    ]
