# Generated by Django 2.2.16 on 2021-10-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20211012_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
