# Generated by Django 2.2.16 on 2021-10-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20211012_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
