# Generated by Django 2.2.16 on 2021-10-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_auto_20211012_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='slug',
        ),
    ]
