# Generated by Django 2.2.16 on 2021-10-12 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_remove_titles_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='category',
        ),
    ]
