# Generated by Django 2.2.16 on 2021-10-12 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_remove_titles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='media.Categories'),
        ),
    ]
