# Generated by Django 2.2.16 on 2021-10-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0013_titles_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='category',
        ),
    ]
