# Generated by Django 2.2.16 on 2021-10-12 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0014_remove_titles_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(blank=True, related_name='titles', to='media.Genres', verbose_name='Жанр'),
        ),
    ]
